Add CI check ensuring no flake.lock file is committed

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,6 +14,12 @@ jobs:
       - uses: "actions/checkout@v4"
       - uses: "DeterminateSystems/nix-installer-action@main"
       - uses: "DeterminateSystems/magic-nix-cache-action@main"
+      - name: Ensure no flake.lock is committed
+        run: |
+          if [ -f flake.lock ]; then
+            echo "flake.lock found, failing the workflow"
+            exit 1
+          fi
       - name: Check formatting
         if: success() || failure()
         run: |
